# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnelAssist
                                 A QGIS plugin
 Helps in assisting for Enel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-08
        copyright            : (C) 2024 by Ionela
        email                : ioneladumitra@yahoo.ro
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EnelAssist class from file EnelAssist.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .enel_assist import EnelAssist
    return EnelAssist(iface)
